version: '3.8'

services:
  # CDN/Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    container_name: bigmind-cdn
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cache-rules.conf:/etc/nginx/conf.d/cache-rules.conf:ro
      - nginx_cache:/var/cache/nginx
      - nginx_logs:/var/log/nginx
    networks:
      - bigmind_network
    restart: unless-stopped
    depends_on:
      - verdaccio
      - origin
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Verdaccio (from Sprint 1)
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: bigmind-verdaccio
    expose:
      - "4873"
    volumes:
      - ../verdaccio/config.yaml:/verdaccio/conf/config.yaml:ro
      - verdaccio_storage:/verdaccio/storage
    networks:
      - bigmind_network
    restart: unless-stopped

  # Origin server (placeholder for actual API)
  origin:
    image: nginx:1.25-alpine
    container_name: bigmind-origin
    expose:
      - "8080"
    volumes:
      - origin_data:/usr/share/nginx/html
    networks:
      - bigmind_network
    restart: unless-stopped

networks:
  bigmind_network:
    driver: bridge

volumes:
  nginx_cache:
  nginx_logs:
  verdaccio_storage:
  origin_data:
